# Generated by Django 5.1.2 on 2024-10-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecording',
            name='created_at',
        ),
        migrations.AlterModelTable(
            name='audiorecording',
            table='audio_recording',
        ),
    ]
