# Generated by Django 4.1.13 on 2024-12-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_processor', '0005_audiofile_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='recorded_file_path',
            field=models.FileField(blank=True, null=True, upload_to='recorded_audio/'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
